"""Tests for the internal gateway key issuer.

Every key here is generated by the command itself into ``tmp_path``. No real key,
credential, or token is involved.
"""

from __future__ import annotations

import json
import re
import stat
from pathlib import Path

import pytest

from butterfly_guy.schwab_gateway.auth import InternalKeyAuthenticator
from butterfly_guy.scripts import issue_gateway_keys as issuer


def _run(tmp_path: Path, *clients: str) -> tuple[Path, str]:
    output = tmp_path / "schwab-gateway-keys.json"
    argv = ["--output", str(output)]
    for client in clients:
        argv += ["--client", client]
    issuer.main(argv)
    return output, output.read_text(encoding="utf-8")


def test_written_file_is_private(tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    output, _ = _run(tmp_path, "butterfly-guy")
    capsys.readouterr()

    mode = stat.S_IMODE(output.stat().st_mode)
    assert mode == 0o600
    # Never group- or world-writable, which the loader also enforces.
    assert not mode & 0o022


def test_file_contains_digests_and_never_the_keys(
    tmp_path: Path, capsys: pytest.CaptureFixture
) -> None:
    output, contents = _run(tmp_path, "butterfly-guy", "equity-scanner")
    printed = capsys.readouterr().out

    keys = re.findall(r"^(?:butterfly-guy|equity-scanner): (.+)$", printed, re.MULTILINE)
    assert len(keys) == 2
    for key in keys:
        assert key not in contents

    payload = json.loads(contents)
    for client in payload["clients"]:
        assert re.fullmatch(r"[0-9a-f]{64}", client["key_sha256"])


def test_printed_keys_hash_to_the_written_digests(
    tmp_path: Path, capsys: pytest.CaptureFixture
) -> None:
    output, _ = _run(tmp_path, "butterfly-guy", "equity-scanner", "afterhours-lab")
    printed = capsys.readouterr().out

    payload = json.loads(output.read_text(encoding="utf-8"))
    digests = {client["id"]: client["key_sha256"] for client in payload["clients"]}

    found = dict(re.findall(r"^(\S+): (\S+)$", printed, re.MULTILINE))
    assert set(found) == set(digests)
    for client_id, key in found.items():
        assert issuer.key_digest(key) == digests[client_id]


def test_written_file_loads_under_the_real_authenticator(
    tmp_path: Path, capsys: pytest.CaptureFixture
) -> None:
    output, _ = _run(tmp_path, "butterfly-guy", "equity-scanner", "afterhours-lab")
    printed = capsys.readouterr().out

    authenticator = InternalKeyAuthenticator.from_file(output)
    found = dict(re.findall(r"^(\S+): (\S+)$", printed, re.MULTILINE))

    for client_id, key in found.items():
        principal = authenticator.authenticate(key)
        assert principal is not None
        assert principal.client_id == client_id
        assert "market_data:read" in principal.capabilities


def test_an_unissued_key_does_not_authenticate(
    tmp_path: Path, capsys: pytest.CaptureFixture
) -> None:
    output, _ = _run(tmp_path, "butterfly-guy")
    capsys.readouterr()

    authenticator = InternalKeyAuthenticator.from_file(output)
    assert authenticator.authenticate(issuer.generate_key()) is None
    assert authenticator.authenticate("") is None


def test_priority_classes_match_the_fixed_identities(
    tmp_path: Path, capsys: pytest.CaptureFixture
) -> None:
    output, _ = _run(tmp_path, "butterfly-guy", "equity-scanner", "afterhours-lab")
    capsys.readouterr()

    payload = json.loads(output.read_text(encoding="utf-8"))
    by_id = {client["id"]: client["priority_class"] for client in payload["clients"]}
    assert by_id == {
        "butterfly-guy": "protected",
        "equity-scanner": "background",
        "afterhours-lab": "background",
    }


def test_existing_output_is_never_overwritten(tmp_path: Path) -> None:
    output = tmp_path / "schwab-gateway-keys.json"
    output.write_text("do not clobber", encoding="utf-8")

    with pytest.raises(SystemExit) as exc:
        issuer.main(["--output", str(output), "--client", "butterfly-guy"])
    assert exc.value.code == 2
    assert output.read_text(encoding="utf-8") == "do not clobber"


@pytest.mark.parametrize(
    "clients",
    [
        pytest.param([], id="no_clients"),
        pytest.param(["not-a-real-client"], id="unknown_client"),
        pytest.param(["butterfly-guy", "butterfly-guy"], id="duplicate_client"),
    ],
)
def test_invalid_client_selections_are_refused(tmp_path: Path, clients: list[str]) -> None:
    output = tmp_path / "schwab-gateway-keys.json"
    argv = ["--output", str(output)]
    for client in clients:
        argv += ["--client", client]

    with pytest.raises(SystemExit) as exc:
        issuer.main(argv)
    assert exc.value.code == 2
    assert not output.exists()


def test_each_run_issues_distinct_keys(tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    (tmp_path / "a").mkdir()
    (tmp_path / "b").mkdir()

    _run(tmp_path / "a", "butterfly-guy")
    first = capsys.readouterr().out
    _run(tmp_path / "b", "butterfly-guy")
    second = capsys.readouterr().out

    assert first != second
