"""Tests for the internal gateway key issuer.

Every key here is generated by the command itself into ``tmp_path``. No real key,
credential, or token is involved.
"""

from __future__ import annotations

import json
import re
import stat
from pathlib import Path

import pytest

from butterfly_guy.schwab_gateway.auth import InternalKeyAuthenticator
from butterfly_guy.scripts import issue_gateway_keys as issuer


def _run(tmp_path: Path, *clients: str) -> tuple[Path, str]:
    output = tmp_path / "schwab-gateway-keys.json"
    argv = ["--output", str(output)]
    for client in clients:
        argv += ["--client", client]
    issuer.main(argv)
    return output, output.read_text(encoding="utf-8")


def test_written_file_is_private(tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    output, _ = _run(tmp_path, "butterfly-guy")
    capsys.readouterr()

    mode = stat.S_IMODE(output.stat().st_mode)
    assert mode == 0o600
    # Never group- or world-writable, which the loader also enforces.
    assert not mode & 0o022


def test_file_contains_digests_and_never_the_keys(
    tmp_path: Path, capsys: pytest.CaptureFixture
) -> None:
    output, contents = _run(tmp_path, "butterfly-guy", "equity-scanner")
    printed = capsys.readouterr().out

    keys = re.findall(r"^(?:butterfly-guy|equity-scanner): (.+)$", printed, re.MULTILINE)
    assert len(keys) == 2
    for key in keys:
        assert key not in contents

    payload = json.loads(contents)
    for client in payload["clients"]:
        assert re.fullmatch(r"[0-9a-f]{64}", client["key_sha256"])


def test_printed_keys_hash_to_the_written_digests(
    tmp_path: Path, capsys: pytest.CaptureFixture
) -> None:
    output, _ = _run(tmp_path, "butterfly-guy", "equity-scanner", "afterhours-lab")
    printed = capsys.readouterr().out

    payload = json.loads(output.read_text(encoding="utf-8"))
    digests = {client["id"]: client["key_sha256"] for client in payload["clients"]}

    found = dict(re.findall(r"^(\S+): (\S+)$", printed, re.MULTILINE))
    assert set(found) == set(digests)
    for client_id, key in found.items():
        assert issuer.key_digest(key) == digests[client_id]


def test_written_file_loads_under_the_real_authenticator(
    tmp_path: Path, capsys: pytest.CaptureFixture
) -> None:
    output, _ = _run(tmp_path, "butterfly-guy", "equity-scanner", "afterhours-lab")
    printed = capsys.readouterr().out

    authenticator = InternalKeyAuthenticator.from_file(output)
    found = dict(re.findall(r"^(\S+): (\S+)$", printed, re.MULTILINE))

    for client_id, key in found.items():
        principal = authenticator.authenticate(key)
        assert principal is not None
        assert principal.client_id == client_id
        assert "market_data:read" in principal.capabilities


def test_an_unissued_key_does_not_authenticate(
    tmp_path: Path, capsys: pytest.CaptureFixture
) -> None:
    output, _ = _run(tmp_path, "butterfly-guy")
    capsys.readouterr()

    authenticator = InternalKeyAuthenticator.from_file(output)
    assert authenticator.authenticate(issuer.generate_key()) is None
    assert authenticator.authenticate("") is None


def test_priority_classes_match_the_fixed_identities(
    tmp_path: Path, capsys: pytest.CaptureFixture
) -> None:
    output, _ = _run(tmp_path, "butterfly-guy", "equity-scanner", "afterhours-lab")
    capsys.readouterr()

    payload = json.loads(output.read_text(encoding="utf-8"))
    by_id = {client["id"]: client["priority_class"] for client in payload["clients"]}
    assert by_id == {
        "butterfly-guy": "protected",
        "equity-scanner": "background",
        "afterhours-lab": "background",
    }


def test_existing_output_is_never_overwritten(tmp_path: Path) -> None:
    output = tmp_path / "schwab-gateway-keys.json"
    output.write_text("do not clobber", encoding="utf-8")

    with pytest.raises(SystemExit) as exc:
        issuer.main(["--output", str(output), "--client", "butterfly-guy"])
    assert exc.value.code == 2
    assert output.read_text(encoding="utf-8") == "do not clobber"


@pytest.mark.parametrize(
    "clients",
    [
        pytest.param([], id="no_clients"),
        pytest.param(["not-a-real-client"], id="unknown_client"),
        pytest.param(["butterfly-guy", "butterfly-guy"], id="duplicate_client"),
    ],
)
def test_invalid_client_selections_are_refused(tmp_path: Path, clients: list[str]) -> None:
    output = tmp_path / "schwab-gateway-keys.json"
    argv = ["--output", str(output)]
    for client in clients:
        argv += ["--client", client]

    with pytest.raises(SystemExit) as exc:
        issuer.main(argv)
    assert exc.value.code == 2
    assert not output.exists()


def test_each_run_issues_distinct_keys(tmp_path: Path, capsys: pytest.CaptureFixture) -> None:
    (tmp_path / "a").mkdir()
    (tmp_path / "b").mkdir()

    _run(tmp_path / "a", "butterfly-guy")
    first = capsys.readouterr().out
    _run(tmp_path / "b", "butterfly-guy")
    second = capsys.readouterr().out

    assert first != second


def test_append_preserves_existing_digest_and_prints_only_new_key(
    tmp_path: Path,
    capsys: pytest.CaptureFixture,
) -> None:
    existing = tmp_path / "existing.json"
    original_document, original_plaintext = issuer.build_keys_document(
        ["butterfly-guy"]
    )
    issuer.write_private_json(existing, original_document)
    output = tmp_path / "appended.json"

    issuer.main(
        [
            "--existing-input",
            str(existing),
            "--output",
            str(output),
            "--client",
            "equity-scanner",
        ]
    )
    printed = capsys.readouterr().out

    original_payload = json.loads(existing.read_text(encoding="utf-8"))
    output_payload = json.loads(output.read_text(encoding="utf-8"))
    original_digest = original_payload["clients"][0]["key_sha256"]
    assert output_payload["clients"][0] == original_payload["clients"][0]
    assert output_payload["clients"][0]["key_sha256"] == original_digest
    assert "butterfly-guy:" not in printed

    new_keys = dict(re.findall(r"^(\S+): (\S+)$", printed, re.MULTILINE))
    assert set(new_keys) == {"equity-scanner"}
    assert "Added 1 new digest(s); wrote 2 total digest(s)" in printed
    authenticator = InternalKeyAuthenticator.from_file(output)
    assert (
        authenticator.authenticate(original_plaintext["butterfly-guy"]).client_id
        == "butterfly-guy"
    )
    assert (
        authenticator.authenticate(new_keys["equity-scanner"]).client_id
        == "equity-scanner"
    )
    assert stat.S_IMODE(output.stat().st_mode) == 0o600


def test_append_rejects_client_already_in_existing_document(
    tmp_path: Path,
) -> None:
    existing = tmp_path / "existing.json"
    document, _ = issuer.build_keys_document(["butterfly-guy"])
    issuer.write_private_json(existing, document)
    output = tmp_path / "appended.json"

    with pytest.raises(SystemExit) as exc:
        issuer.main(
            [
                "--existing-input",
                str(existing),
                "--output",
                str(output),
                "--client",
                "butterfly-guy",
            ]
        )

    assert exc.value.code == 2
    assert not output.exists()


@pytest.mark.parametrize(
    "mutation",
    [
        pytest.param(
            lambda payload: payload["clients"][0].update(id="unknown-client"),
            id="unknown_existing_client",
        ),
        pytest.param(
            lambda payload: payload["clients"].append(dict(payload["clients"][0])),
            id="duplicate_existing_client",
        ),
    ],
)
def test_append_rejects_existing_document_the_authenticator_rejects(
    tmp_path: Path,
    mutation,
) -> None:
    existing = tmp_path / "existing.json"
    document, _ = issuer.build_keys_document(["butterfly-guy"])
    mutation(document)
    issuer.write_private_json(existing, document)
    output = tmp_path / "appended.json"

    with pytest.raises(SystemExit) as exc:
        issuer.main(
            [
                "--existing-input",
                str(existing),
                "--output",
                str(output),
                "--client",
                "equity-scanner",
            ]
        )

    assert exc.value.code == 2
    assert not output.exists()


def test_append_never_overwrites_existing_output(tmp_path: Path) -> None:
    existing = tmp_path / "existing.json"
    document, _ = issuer.build_keys_document(["butterfly-guy"])
    issuer.write_private_json(existing, document)
    output = tmp_path / "appended.json"
    output.write_text("do not clobber", encoding="utf-8")

    with pytest.raises(SystemExit) as exc:
        issuer.main(
            [
                "--existing-input",
                str(existing),
                "--output",
                str(output),
                "--client",
                "equity-scanner",
            ]
        )

    assert exc.value.code == 2
    assert output.read_text(encoding="utf-8") == "do not clobber"
